name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libmpv-dev
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}
      - name: Build project
        run: |
          make
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_tag_name.outputs.tag_name }}
          draft: true
          files: lib/mpv_inhibit_gnome.so
